"""Create and audit a portable Court35 deployment package.

The locked P01--P35 layout is retained for the published study.  This module
turns the same geometry into an explicit, site-specific deployment record for
another regulation badminton court.  It deliberately does not infer camera
calibration or claim spatial accuracy from a template alone.
"""

from __future__ import annotations

import csv
import json
import tomllib
from pathlib import Path
from typing import Any

from .control_points import (
    expected_control_points,
    read_control_points,
    validate_control_points,
    write_control_points,
)


COURT_NOMINAL_M = {
    "full_court_length_m": 13.40,
    "doubles_court_width_m": 6.10,
    "singles_court_width_m": 5.18,
    "net_center_height_m": 1.524,
    "net_post_height_m": 1.55,
    "short_service_line_from_net_m": 1.98,
    "doubles_long_service_line_from_back_m": 0.76,
}
DIMENSION_TOLERANCE_M = 0.02
CAMERA_COLUMNS = (
    "Camera_ID",
    "Position_Label",
    "Camera_Model",
    "Lens_or_FOV",
    "Resolution_px",
    "Frame_Rate_Hz",
    "Intrinsics_Calibrated",
    "Extrinsics_Calibrated",
    "Coverage_Test_Passed",
    "Fixed_After_Calibration",
    "Notes",
)
IMU_COLUMNS = (
    "Device_ID",
    "Body_Location",
    "Manufacturer_Model",
    "Firmware",
    "Sample_Rate_Hz",
    "Axis_Convention_Recorded",
    "Clock_or_Sync_Method",
    "Mounting_Photo_Recorded",
    "Notes",
)


def _write_csv(path: Path, columns: tuple[str, ...], rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)


def _as_bool(value: object) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes", "y", "pass", "passed"}


def _load_toml(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def _site_toml(site_name: str) -> str:
    return f'''# Court35 site deployment record. Complete this file before acquisition.
[site]
name = {json.dumps(site_name, ensure_ascii=False)}
court_standard = "Regulation badminton doubles court (nominal geometry)"
coordinate_system = "Origin at the net centre; X lateral, Y net-to-backcourt, Z vertical; metres"
full_court_length_m = 13.40
doubles_court_width_m = 6.10
singles_court_width_m = 5.18
net_center_height_m = 1.524
net_post_height_m = 1.55
short_service_line_from_net_m = 1.98
doubles_long_service_line_from_back_m = 0.76

[acquisition]
visual_frame_rate_hz = 60
imu_sample_rate_hz = 50
shared_sync_event = "Record the same LED, clap, or impact event in every stream"

[validation]
court_survey_confirmed = false
intrinsic_calibration_confirmed = false
extrinsic_calibration_confirmed = false
coverage_test_confirmed = false
synchronization_event_confirmed = false
held_out_3d_validation_confirmed = false
'''


def _site_readme() -> str:
    return """# New-site deployment package

This folder is generated by `court35 scaffold-site`. It is a site record, not
a calibration result. Complete `site.toml`, `camera_manifest.csv` and
`imu_manifest.csv`; preserve the exported P01--P35 click order; then run
`court35 validate-site --site-dir . --report deployment_report.json`.

`READY_FOR_RELATIVE_ANALYSIS` means the recorded deployment prerequisites are
complete. It does **not** establish absolute 3-D accuracy. Only a documented
held-out spatial validation can produce `READY_WITH_HELD_OUT_VALIDATION`.
"""


def create_site_package(output_dir: str | Path, site_name: str) -> dict[str, object]:
    """Generate a portable deployment template without overwriting a site folder."""
    root = Path(output_dir)
    if root.exists() and any(root.iterdir()):
        raise ValueError(f"Refusing to overwrite non-empty deployment directory: {root}")
    root.mkdir(parents=True, exist_ok=True)
    (root / "site.toml").write_text(_site_toml(site_name), encoding="utf-8")
    (root / "README.md").write_text(_site_readme(), encoding="utf-8")
    control_path = write_control_points(expected_control_points(), root / "calibration" / "scene_points_click_order.csv")
    _write_csv(
        root / "camera_manifest.csv",
        CAMERA_COLUMNS,
        [
            {
                "Camera_ID": f"cam{index:02d}",
                "Position_Label": label,
                "Camera_Model": "",
                "Lens_or_FOV": "",
                "Resolution_px": "",
                "Frame_Rate_Hz": "60",
                "Intrinsics_Calibrated": "false",
                "Extrinsics_Calibrated": "false",
                "Coverage_Test_Passed": "false",
                "Fixed_After_Calibration": "false",
                "Notes": "Complete after local setup.",
            }
            for index, label in enumerate(("near-left", "near-right", "far-left", "far-right"), start=1)
        ],
    )
    _write_csv(
        root / "imu_manifest.csv",
        IMU_COLUMNS,
        [
            {
                "Device_ID": device,
                "Body_Location": location,
                "Manufacturer_Model": "",
                "Firmware": "",
                "Sample_Rate_Hz": "50",
                "Axis_Convention_Recorded": "false",
                "Clock_or_Sync_Method": "",
                "Mounting_Photo_Recorded": "false",
                "Notes": "Complete only for sensors used at this site.",
            }
            for device, location in (("imu_hand", "racket-side hand"), ("imu_left_knee", "left knee"), ("imu_right_knee", "right knee"))
        ],
    )
    (root / "calibration" / "README.md").write_text(
        "Use the P01--P35 coordinates as the extrinsic-calibration object points. "
        "Do not move any camera after recording all targets. Store the camera-specific "
        "intrinsics, extrinsics, residual table and calibration image/video paths beside this file.\n",
        encoding="utf-8",
    )
    return {
        "status": "TEMPLATE_CREATED",
        "site_dir": root.as_posix(),
        "control_points_csv": control_path.as_posix(),
        "next_command": f'court35 validate-site --site-dir "{root}" --report deployment_report.json',
    }


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def _missing_columns(rows: list[dict[str, str]], required: tuple[str, ...]) -> list[str]:
    return sorted(set(required) - (set(rows[0]) if rows else set()))


def validate_site_package(site_dir: str | Path) -> dict[str, object]:
    """Audit whether a new court has enough recorded evidence for the pipeline.

    The report distinguishes an executable relative-analysis deployment from
    independently validated absolute spatial accuracy.
    """
    root = Path(site_dir)
    blockers: list[str] = []
    reviews: list[str] = []
    evidence: dict[str, object] = {"site_dir": root.as_posix()}
    config_path = root / "site.toml"
    if not config_path.exists():
        return {"status": "BLOCKED", "blockers": ["site.toml is missing"], "review_items": [], **evidence}
    try:
        config = _load_toml(config_path)
    except tomllib.TOMLDecodeError as exc:
        return {"status": "BLOCKED", "blockers": [f"site.toml is invalid: {exc}"], "review_items": [], **evidence}
    site = config.get("site", {})
    validation = config.get("validation", {})
    evidence["site_name"] = site.get("name", "")
    dimension_checks: dict[str, object] = {}
    for key, nominal in COURT_NOMINAL_M.items():
        try:
            actual = float(site[key])
            passed = abs(actual - nominal) <= DIMENSION_TOLERANCE_M
        except (KeyError, TypeError, ValueError):
            actual, passed = None, False
        dimension_checks[key] = {"configured_m": actual, "nominal_m": nominal, "passed": passed}
        if not passed:
            blockers.append(f"{key} is absent or differs from nominal regulation geometry by more than {DIMENSION_TOLERANCE_M:.2f} m")
    evidence["court_dimension_checks"] = dimension_checks

    control_path = root / "calibration" / "scene_points_click_order.csv"
    if not control_path.exists():
        blockers.append("calibration/scene_points_click_order.csv is missing")
    else:
        try:
            control_report = validate_control_points(read_control_points(control_path))
            evidence["control_points"] = control_report
            if control_report["status"] != "PASS":
                blockers.append("P01--P35 calibration layout failed validation")
        except ValueError as exc:
            blockers.append(f"control-point CSV cannot be read: {exc}")

    camera_path = root / "camera_manifest.csv"
    if not camera_path.exists():
        blockers.append("camera_manifest.csv is missing")
    else:
        rows = _read_csv(camera_path)
        missing = _missing_columns(rows, CAMERA_COLUMNS)
        if missing:
            blockers.append(f"camera manifest missing columns: {', '.join(missing)}")
        else:
            ids = {row["Camera_ID"].strip() for row in rows if row["Camera_ID"].strip()}
            evidence["camera_ids"] = sorted(ids)
            if len(ids) != 4:
                blockers.append(f"exactly four unique cameras are required; found {len(ids)}")
            for field, label in (
                ("Intrinsics_Calibrated", "intrinsic calibration"),
                ("Extrinsics_Calibrated", "extrinsic calibration"),
                ("Coverage_Test_Passed", "full-body/racket-apex coverage test"),
                ("Fixed_After_Calibration", "camera fixation after calibration"),
            ):
                incomplete = [row.get("Camera_ID", "?") for row in rows if not _as_bool(row.get(field, ""))]
                if incomplete:
                    reviews.append(f"{label} is not confirmed for: {', '.join(incomplete)}")

    required_flags = (
        "court_survey_confirmed",
        "intrinsic_calibration_confirmed",
        "extrinsic_calibration_confirmed",
        "coverage_test_confirmed",
        "synchronization_event_confirmed",
    )
    missing_flags = [name for name in required_flags if not _as_bool(validation.get(name, False))]
    if missing_flags:
        reviews.append("site.toml validation flags not confirmed: " + ", ".join(missing_flags))
    held_out_confirmed = _as_bool(validation.get("held_out_3d_validation_confirmed", False))
    if blockers:
        status = "BLOCKED"
    elif reviews:
        status = "REVIEW_REQUIRED"
    elif held_out_confirmed:
        status = "READY_WITH_HELD_OUT_VALIDATION"
    else:
        status = "READY_FOR_RELATIVE_ANALYSIS"
        reviews.append("No held-out 3-D validation is recorded; do not claim absolute spatial accuracy.")
    return {
        "status": status,
        "blockers": blockers,
        "review_items": reviews,
        "absolute_accuracy_claim": "SUPPORTED_ONLY_WITH_HELD_OUT_VALIDATION" if held_out_confirmed and not blockers else "NOT_ESTABLISHED",
        "relative_analysis_deployment": status in {"READY_FOR_RELATIVE_ANALYSIS", "READY_WITH_HELD_OUT_VALIDATION"},
        **evidence,
    }
